@echo off
setlocal
call "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
if errorlevel 1 exit /b 1
cd /d "%~dp0..\llama.cpp\build\common"
cl /c /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\COMMON\." /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\VENDOR\NLOHMANN\.." /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\VENDOR\SHEREDOM\.." /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\SRC\..\INCLUDE" /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\GGML\SRC\..\INCLUDE" /I"C:\PROGRAM FILES\NVIDIA GPU COMPUTING TOOLKIT\CUDA\V13.3\INCLUDE" /nologo /W1 /WX- /diagnostics:column /O2 /Ob2 /D _WINDLL /D _MBCS /D WIN32 /D _WINDOWS /D NDEBUG /D LLAMA_SUBPROCESS /D _CRT_SECURE_NO_WARNINGS /D LLAMA_SHARED /D GGML_USE_CPU /D GGML_USE_CUDA /D GGML_SHARED /D GGML_BACKEND_SHARED /D "CMAKE_INTDIR=\"Release\"" /D llama_common_EXPORTS /EHsc /MD /std:c++17 /Fo"LLAMA-COMMON.DIR\RELEASE\\" /Fd"LLAMA-COMMON.DIR\RELEASE\VC145.PDB" /external:W1 /TP  /utf-8 /bigobj C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\COMMON\SPECULATIVE.CPP
if errorlevel 1 exit /b 1
link @"%~dp0..\experiments\runtime_audit\mtp_sources\common-link.rsp"
exit /b %errorlevel%
