@echo off
setlocal
call "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
if errorlevel 1 exit /b 1
cd /d "%~dp0..\llama.cpp\build\tools\server"
cl /c /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\TOOLS\SERVER" /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\BUILD\TOOLS\SERVER" /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\TOOLS\SERVER\..\MTMD" /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP" /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\COMMON\." /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\VENDOR\NLOHMANN\.." /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\VENDOR\SHEREDOM\.." /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\SRC\..\INCLUDE" /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\GGML\SRC\..\INCLUDE" /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\TOOLS\MTMD\." /I"C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\BUILD\TOOLS\UI" /I"C:\PROGRAM FILES\NVIDIA GPU COMPUTING TOOLKIT\CUDA\V13.3\INCLUDE" /nologo /W1 /WX- /diagnostics:column /O2 /Ob2 /D _WINDLL /D _MBCS /D WIN32 /D _WINDOWS /D NDEBUG /D _CRT_SECURE_NO_WARNINGS /D LLAMA_SUBPROCESS /D LLAMA_SHARED /D GGML_USE_CPU /D GGML_USE_CUDA /D GGML_SHARED /D GGML_BACKEND_SHARED /D "CMAKE_INTDIR=\"Release\"" /D llama_server_impl_EXPORTS /EHsc /MD /std:c++17 /Fo"LLAMA-SERVER-IMPL.DIR\RELEASE\\" /Fd"LLAMA-SERVER-IMPL.DIR\RELEASE\VC145.PDB" /external:W1 /TP  /utf-8 /bigobj C:\USERS\ALI\WEBPROJECTS\ATLAS-ENGINE-V1\LLAMA.CPP\TOOLS\SERVER\SERVER-HTTP.CPP
if errorlevel 1 exit /b 1
"C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E __create_def llama-server-impl.dir/Release/exports.def llama-server-impl.dir/Release/objects.txt
if errorlevel 1 exit /b 1
link @"%~dp0..\experiments\runtime_audit\mtp_sources\server-link.rsp"
exit /b %errorlevel%
